language: scala
sudo: false
scala:
  - 2.10.6
  - 2.11.7
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
scripts:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
before_script:
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar